spring:
  application:
    name: api-gateway
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.32.111:9411/
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: service-hi
          uri: lb://service-hi
          predicates:
            - Path=/service-hi/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1
        - id: service-file
          uri: lb://service-file
          predicates:
            - Path=/service-file/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1
        - id: service-hi-react
          uri: lb://service-hi-react
          predicates:
            - Path=/service-hi-react/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1
        - id: service-feign
          uri: lb://service-feign
          predicates:
            - Path=/service-feign/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1

server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 10

logging:
  level:
    org.springframework.cloud.gateway: debug