spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: service-hi
          uri: lb://service-hi
          predicates:
            - Path=/service-hi/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1
        - id: service-file
          uri: lb://service-file
          predicates:
            - Path=/service-file/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1



server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 10

logging:
  level:
    org.springframework.cloud.gateway: debug