spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.138.52:3306/ckshop?serverTimezone=GMT%2B8
    username: root
    password: 123456
  data:
    mongodb:
      host: 192.168.138.54
      port: 27017
      database: test
  profiles:
    active: dev
mybatis:
  mapper-locations: #mapper/*Mapper.xml
  type-aliases-package: #com.fast.cloud.biz.bean.*
  configuration:
    map-underscore-to-camel-case: true

mapper:
  identity: MYSQL
  mappers:
    - tk.mybatis.mapper.common.BaseMapper
  not-empty: true
  enum-as-simple-type: true


pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: ture
  params: count=countSql

#打印sql
logging:
  level:
    com.fast.cloud: debug

ck:
  swagger:
    title: APIs
    description: 微服务<font color="red">test模块</font>接口文档
    version: 1.0
    modules:
      - {
        model-name: ck-content,
        packages: ["com.fast.cloud.biz.controller"],
        group-name: ck-content,
        name: ck-content,
        location: "/admin/service-content/v2/api-docs?group=ck-content",
        version: 2.0
      }