spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.32.111:3306/mall?serverTimezone=GMT%2B8
    username: root
    password: root
  data:
    mongodb:
      host: 192.168.32.111
      port: 27017
      database: test
  profiles:
    active: dev
  messages:
    basename: i18n/messages
mybatis:
  mapper-locations: #mapper/*Mapper.xml
  type-aliases-package: #com.fast.cloud.biz.bean.*
  configuration:
    map-underscore-to-camel-case: true

mapper:
  identity: MYSQL
  mappers:
    - tk.mybatis.mapper.common.BaseMapper
  not-empty: true
  enum-as-simple-type: true


pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: ture
  params: count=countSql

#打印sql
logging:
  level:
    com.fast.cloud: debug

ck:
  swagger:
    title: api manage RESTful Content APIs
    description: <font color="red">接口文档</font>
    version: 1.0
    modules:
    - {
      model-name: model_one,
      packages: ["com.fast.cloud.biz.controller"],
      group-name: model_one
    }
  test:
    map-config:
      hello:
        hello: hello
        aaa: aaa
      master:
        hello: master
        aaa: masterAAA