server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka01:8761/eureka/
    registry-fetch-interval-seconds: 10

spring:
  application:
    name: eurka-server

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS